### ISSUE TITLE
Add license to QCommandPalette

### ISSUE THREAD

**Issue by ITAYC0HEN** [theHamsta/QCommandPalette#1]
Hey there! 
Thank you for the project :)

It seems like currently, QCommandPalette does not specify any LICENSE, in comments or in a LICENSE file. This prevents the community from using the project.

Please add the license which you feel that best describes the way you want the community to use and modify this project. 

I suggest going to the website GitHub created for this subject -> https://choosealicense.com

We would be happy to use this project and modify it to our needs. Thank you!

**Comment by theHamsta** [comment]
Thanks for the interest. I licensed it with MIT license. Have fun with it!

**Comment by theHamsta** [comment]
I made this more as a personal project. I didn't know how to do the popup close correctly with Qt. Please let me know if you a better way how to do it!

**Comment by ITAYC0HEN** [comment]
> I made this more as a personal project

That's great! We need more people to do "personal projects" in [Cutter](https://github.com/radareorg/cutter) codebase :) If you have some spare time to do some Qt open-source in a highly popular project, we will be happy to have you :)
